//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaneBombGame.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlaneBombGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 5 5 0 2 8 2 2 3 2
        ///5 5 2 2 8 2 2 3 2
        ///5 6 0 2 8 2 2 3 2
        ///5 6 2 2 8 2 2 3 2
        ///6 3 2 2 8 2 2 3 2
        ///6 4 2 2 8 2 2 3 2
        ///6 5 1 2 8 2 2 3 2
        ///6 5 2 2 8 2 2 3 2
        ///6 5 3 2 8 2 2 3 2
        ///6 6 1 2 8 2 2 3 2
        ///6 6 2 2 8 2 2 3 2
        ///6 6 3 2 8 2 2 3 2
        ///6 7 2 2 8 2 2 3 2
        ///6 8 2 2 8 2 2 3 2
        ///7 2 3 2 8 2 2 3 2
        ///7 3 0 2 8 2 2 3 2
        ///7 3 1 2 8 2 2 3 2
        ///7 3 2 2 8 2 2 3 2
        ///7 3 3 2 8 2 2 3 2
        ///7 4 0 2 8 2 2 3 2
        ///7 4 1 2 8 2 2 3 2
        ///7 4 2 2 8 2 2 3 2
        ///7 4 3 2 8 2 2 3 2
        ///7 5 0 2 8 2 2 3 2
        ///7 5 1 2 8 2 2 3 2
        ///7 5 2 2 8 2 2 3 2
        ///7 5 3 2 8 2 2 3 2        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon_已去底_ {
            get {
                object obj = ResourceManager.GetObject("icon_已去底_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 击中 {
            get {
                object obj = ResourceManager.GetObject("击中", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 爆炸 {
            get {
                object obj = ResourceManager.GetObject("爆炸", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
